---
- name: Install Webtatic Repo
  yum:
    name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    state: installed

- name: Set httpd service to stopped
  service: name=httpd state=stopped

- name: Install php packages
  yum: name={{item}} state=installed
  with_items:
       - php56w
       - php56w-common
       - php56w-mbstring 
       - php56w-gd
       - php56w-bcmath
       - php56w-mcrypt
       - php56w-tidy
       - php56w-xml
       - php56w-xmlrpc
       - php56w-soap
       - php56w-mysql
       - php56w-pdo
       - php56w-devel

- ini_file: dest=/etc/php.ini
            section=PHP
            option=display_errors
            value=on
            backup=yes

- name: Add php info file
  copy: src=files/phpinfo.php dest=/var/www/html/phpinfo.php

- name: Set httpd service to running
  service: name=httpd state=started