general:
  update: "false"
  name: "bento/centos-7.2"

provider:
  type: "virtualbox"
  gui: false
  ram: "2024"

network:
  networkType: "public_network"
  bridgedAdapter: "en0: Wi-Fi (AirPort)"
  ip: "192.168.0.145"

#Array of sharedFolders
sharedFolders:
  - source: "./TheProvisoner"
    dest: "/Provisionator"

  # - source: "./TheProvisoner2"
  #   dest: "/Provisionator2"

